[build]
rustflags = ["--cfg", "tokio_unstable"]
rustdocflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["--cfg", "tokio_unstable", "-C", "target-feature=+crt-static", "-L", "/var/home/v/proj/libxkbcommon/build-musl", "-C", "link-arg=-static"]

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH_x86_64_unknown_linux_musl = "/usr/x86_64-linux-musl/lib/pkgconfig"
